- name: This playbook will install nginx, configures nginx to use a custom web root folder, deploy a custom web page 
  hosts: all
  gather_facts: no
  tasks:
  - name: Install nginx web server into ubuntu ansible nodes
    apt: name=nginx state=latest update_cache=yes
