- name: This playbook will install nginx, configures nginx to use a custom web root folder, deploy a custom web page 
  hosts: all
  vars:
  - greeting_msg: Welcome to DevOps!
  - conf_mgr_tool: Ansible
  - provisioner_tool: Docker
  tasks:
  - name: Retrieve IP address
    shell: hostname -i
    register: ip_addr

  - debug: var=ip_addr

  - name: Install nginx web server into ubuntu ansible nodes
    when: ansible_distribution == "Ubuntu" and ansible_os_family == "Debian"
    apt: name=nginx state=latest update_cache=yes

  - name: Create the custom web root folder that would serve the html web pages
    file: path=/var/html state=directory mode=0755
      
  - name: Configure the nginx to pick the html page from our custom folder
    when: ansible_distribution == "Ubuntu" and ansible_os_family == "Debian"
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Restart nginx server to apply the config changes
    when: ansible_distribution == "Ubuntu" and ansible_os_family == "Debian"
    shell: service nginx restart

  - name: Deploy our custom web page
    template: src=index.html.j2 dest=/var/html/index.html

