- name: This playbook will build the ansible node custom docker images
  hosts: localhost
  gather_facts: no
  vars:
  - image_names:
    - tektutor/ansible-ubuntu-node:latest
    - tektutor/ansible-centos-node:latest
  vars_files:
  - become-password.yml 
  tasks:
  - name: Delete all ansible node containers 
    shell: docker rm -f $(docker ps -aq --filter="name=ubuntu" --filter="name=centos")
    ignore_errors: yes

  - name: Install pip3 in Ubuntu
    when: ansible_os_family == "Ubuntu"
    apt: name=python3-pip state=latest

  - name: Install pip3 in Fedora,CentOS/RHEL 
    when: ansible_os_family == "RedHat"
    yum: name=python3-pip state=latest

  - name: Install Docker Python SDK
    shell: pip install docker-py

  - name: Delete all ansible node images from local registry
    docker_image:
      name: "{{item}}" 
      state: absent
    with_list: "{{image_names}}"
    ignore_errors: yes

  - name: copy the public into current directory
    copy: src=~/.ssh/id_rsa.pub dest=./authorized_keys 

  - name: Build ubuntu ansible node docker image
    docker_image:
      name: "{{item}}"
      build:
        dockerfile: UbuntuDockerfile
        path: .
        pull: no
      state: present
      source: build
    with_list: "{{image_names}}"

  - name: Delete the authorized_key file from current directory 
    shell: rm ./authorized_keys

  
